"use client";

import { useActionState } from "react";
import { generateSummaryAction } from "@/app/(app)/analytics/actions";
import { Button } from "@/components/ui/button";

export function AiSummary() {
  const [state, action, pending] = useActionState(generateSummaryAction, null);
  return (
    <div>
      {state?.text ? (
        <div className="space-y-3">
          <div className="whitespace-pre-wrap rounded-md bg-muted/50 p-4 text-sm">
            {state.text}
          </div>
          <p className="text-xs text-muted-foreground">Generated by {state.model}</p>
          <form action={action}>
            <Button type="submit" variant="outline" size="sm" disabled={pending}>
              {pending ? "Regenerating…" : "Regenerate"}
            </Button>
          </form>
        </div>
      ) : (
        <form action={action}>
          <p className="mb-3 text-sm text-muted-foreground">
            Generate a plain-English management summary and recommendations from the
            current performance data.
          </p>
          <Button type="submit" disabled={pending}>
            {pending ? "Analysing…" : "Generate AI summary"}
          </Button>
        </form>
      )}
    </div>
  );
}
