import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  marketingPackageCheckoutConfigurationError,
  changeMarketingPackageSubscription,
  mockPackageCheckoutEnabled,
  retrieveMarketingPackageSubscriptionState,
  uniqueSubscriptionItemForPrice,
  verifyMarketingPackageCheckoutSession,
} from "../src/lib/billing";
import {
  applyInvoicePaymentSucceeded,
  applyServiceOptionsEdit,
  checkoutMatchesPendingServiceTransition,
  initialCompanyServiceBilling,
  isCurrentServiceSubscriptionEvent,
  requestPackageChange,
  serviceOperationsAllowed,
} from "../src/lib/managed-service-billing";
import {
  ADMIN_ROLE_LABEL,
  CLIENT_ROLE_LABEL,
  STAFF_ROLE_LABEL,
  clientApprovalSummary,
  containsClientForbiddenWording,
} from "../src/lib/managed-service/client-ux";
import type { ContentItem, ManagedApprovalRequest } from "../src/lib/types";

const stamp = "2026-07-19T00:00:00.000Z";
const content: ContentItem = {
  id: "content-1",
  companyId: "company-1",
  type: "social_post",
  title: "Winter booking campaign",
  body: "Book a table this winter.",
  status: "pending_approval",
  createdById: "staff-1",
  createdAt: stamp,
  updatedAt: stamp,
  versions: [],
  managedChannelKey: "instagram",
};
const request: ManagedApprovalRequest = {
  id: "approval-1",
  tenantId: "tenant-1",
  companyId: "company-1",
  contentId: content.id,
  scope: "standard_content",
  recipientEmail: "owner@example.com",
  tokenHash: "hash",
  status: "pending",
  dueAt: "2026-07-25T00:00:00.000Z",
  revisionRound: 1,
  createdAt: stamp,
  updatedAt: stamp,
};

const summary = clientApprovalSummary({
  content,
  request,
  posts: [
    {
      id: "post-1",
      contentId: content.id,
      companyId: content.companyId,
      platform: "Facebook",
      scheduledDate: "2026-07-30",
      scheduledTime: "09:00",
      status: "scheduled",
      createdById: "staff-1",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
});

assert.equal(summary.revisionsRemaining, 1);
assert.deepEqual(summary.channels, ["Facebook", "Instagram"]);
assert.equal(summary.scheduledFor, "2026-07-30 at 09:00");
assert.deepEqual(
  [ADMIN_ROLE_LABEL, STAFF_ROLE_LABEL, CLIENT_ROLE_LABEL],
  ["Admin", "Staff", "Client Approver"],
);
assert.equal(
  containsClientForbiddenWording(
    [
      summary.purpose,
      summary.scopeLabel,
      summary.channels.join(" "),
      "Approve Request changes",
    ].join(" "),
  ),
  false,
);
assert.equal(containsClientForbiddenWording("generated by a model"), true);

async function reviewFindingChecks() {
  const active = applyInvoicePaymentSucceeded(
    initialCompanyServiceBilling("growth"),
    stamp,
    "2026-08-19T00:00:00.000Z",
  );
  const grace = {
    ...active,
    status: "past_due_grace" as const,
    graceEndsAt: "2026-07-20T00:00:00.000Z",
  };
  assert.equal(serviceOperationsAllowed(undefined, stamp), false);
  assert.equal(
    serviceOperationsAllowed(initialCompanyServiceBilling("starter"), stamp),
    false,
  );
  assert.equal(serviceOperationsAllowed(active, stamp), true);
  assert.equal(serviceOperationsAllowed(grace, stamp), true);
  assert.equal(
    serviceOperationsAllowed(grace, "2026-07-20T00:00:00.000Z"),
    false,
  );

  const paused = { ...active, status: "paused" as const, pausedAt: stamp };
  const optionEdit = applyServiceOptionsEdit(paused, "growth", {
    websitePublishing: true,
  });
  assert.equal(optionEdit.status, "paused");
  assert.equal(optionEdit.serviceOptions.websitePublishing, false);
  assert.equal(optionEdit.pendingServiceOptions?.websitePublishing, true);

  const downgrade = requestPackageChange(
    { ...active, stripeSubscriptionId: "sub_current" },
    "starter",
    stamp,
  );
  assert.equal(
    checkoutMatchesPendingServiceTransition(downgrade, {
      packageId: "starter",
      pendingTransitionId: downgrade.pendingTransitionId,
      pendingChangeKind: "downgrade",
      pendingEffectiveAt: downgrade.pendingEffectiveAt,
    }),
    true,
  );
  assert.equal(
    checkoutMatchesPendingServiceTransition(downgrade, {
      packageId: "managed",
      pendingChangeKind: "upgrade",
    }),
    false,
  );
  assert.equal(
    applyInvoicePaymentSucceeded(downgrade, "2026-07-20T00:00:00.000Z")
      .activePackageId,
    "growth",
  );
  assert.equal(isCurrentServiceSubscriptionEvent(downgrade, "sub_old"), false);
  assert.equal(
    isCurrentServiceSubscriptionEvent(downgrade, "sub_current"),
    true,
  );

  process.env.CC_ENV = "development";
  delete process.env.CC_LOCAL_DEMO;
  delete process.env.NEXT_PUBLIC_CC_LOCAL_DEMO;
  delete process.env.STRIPE_SECRET_KEY;
  assert.equal(mockPackageCheckoutEnabled(), false);
  process.env.CC_LOCAL_DEMO = "true";
  process.env.NEXT_PUBLIC_CC_LOCAL_DEMO = "true";
  assert.equal(mockPackageCheckoutEnabled(), true);
  process.env.STRIPE_SECRET_KEY = "sk_test_config_only";
  process.env.STRIPE_PRICE_PACKAGE_STARTER = "price_starter";
  process.env.STRIPE_PRICE_WEBSITE_CONNECTION_SETUP = "price_setup";
  delete process.env.STRIPE_PRICE_WEBSITE_PUBLISHING;
  assert.match(
    marketingPackageCheckoutConfigurationError("starter", {
      websitePublishing: true,
    }) ?? "",
    /website publishing/,
  );
  assert.equal(
    verifyMarketingPackageCheckoutSession(
      {
        id: "cs_unpaid",
        status: "complete",
        payment_status: "unpaid",
        metadata: {
          kind: "marketing_package",
          tenantId: "tenant-1",
          companyId: "company-1",
        },
      },
      { tenantId: "tenant-1", companyId: "company-1" },
    ).ok,
    false,
  );

  const originalFetch = globalThis.fetch;
  const stripeCalls: string[] = [];
  process.env.STRIPE_PRICE_PACKAGE_GROWTH = "price_growth";
  process.env.STRIPE_PRICE_PACKAGE_MANAGED = "price_managed";
  assert.equal(
    uniqueSubscriptionItemForPrice(
      {
        items: {
          data: [
            { id: "si_one", price: { id: "price_growth" } },
            { id: "si_two", price: { id: "price_growth" } },
          ],
        },
      },
      "price_growth",
    ),
    null,
  );
  let currentItemId = "si_starter";
  let currentPriceId = "price_starter";
  globalThis.fetch = (async (input, init) => {
    const url = String(input);
    stripeCalls.push(`${init?.method ?? "GET"} ${url}`);
    if (init?.method === "POST") {
      const params = new URLSearchParams(String(init.body));
      const nextPriceId = params.get("items[0][price]");
      assert(nextPriceId);
      assert.equal(
        [...params.keys()].some(
          (key) => key.endsWith("[id]") && params.get(key) === currentItemId,
        ),
        true,
      );
      currentPriceId = nextPriceId;
      currentItemId =
        nextPriceId === "price_growth" ? "si_growth" : "si_managed";
    }
    return new Response(
      JSON.stringify({
        id: "sub_one",
        metadata: {
          kind: "marketing_package",
          tenantId: "tenant-1",
          companyId: "company-1",
          packageId:
            currentPriceId === "price_managed"
              ? "managed"
              : currentPriceId === "price_growth"
                ? "growth"
                : "starter",
        },
        items: {
          data: [{ id: currentItemId, price: { id: currentPriceId } }],
        },
      }),
      { status: 200, headers: { "content-type": "application/json" } },
    );
  }) as typeof fetch;
  try {
    const changed = await changeMarketingPackageSubscription({
      tenantId: "tenant-1",
      companyId: "company-1",
      packageId: "growth",
      changeKind: "upgrade",
      billing: {
        ...active,
        activePackageId: "starter",
        stripeSubscriptionId: "sub_one",
        stripeSubscriptionItemId: "si_starter",
        stripePriceId: "price_starter",
      },
    });
    assert.equal(changed.ok, true);
    assert.equal(changed.subscriptionItemId, "si_growth");
    const changedAgain = await changeMarketingPackageSubscription({
      tenantId: "tenant-1",
      companyId: "company-1",
      packageId: "managed",
      changeKind: "upgrade",
      billing: {
        ...active,
        activePackageId: "growth",
        stripeSubscriptionId: changed.subscriptionId,
        stripeSubscriptionItemId: changed.subscriptionItemId,
        stripePriceId: changed.priceId,
      },
    });
    assert.equal(changedAgain.ok, true);
    assert.equal(changedAgain.subscriptionItemId, "si_managed");
    assert.deepEqual(
      await retrieveMarketingPackageSubscriptionState("sub_one", {
        tenantId: "tenant-1",
        companyId: "company-1",
      }),
      {
        subscriptionItemId: "si_managed",
        priceId: "price_managed",
        packageId: "managed",
        cancelAtPeriodEnd: false,
      },
    );
    const missingOptionPrice = await changeMarketingPackageSubscription({
      tenantId: "tenant-1",
      companyId: "company-1",
      packageId: "managed",
      changeKind: "options_upgrade",
      billing: {
        ...active,
        activePackageId: "managed",
        stripeSubscriptionId: changedAgain.subscriptionId,
        stripeSubscriptionItemId: changedAgain.subscriptionItemId,
        stripePriceId: changedAgain.priceId,
      },
      serviceOptions: {
        ...active.serviceOptions,
        searchVisibility: true,
        websitePublishing: true,
      },
    });
    assert.deepEqual(missingOptionPrice, {
      ok: false,
      reason: "missing_recurring_price_configuration",
    });
    assert.equal(
      stripeCalls.filter((call) => call.startsWith("POST")).length,
      2,
    );
    assert.equal(
      stripeCalls.some((call) => call.includes("/checkout/sessions")),
      false,
    );
  } finally {
    globalThis.fetch = originalFetch;
  }

  const migration48 = readFileSync(
    new URL(
      "../supabase/legacy-migrations/0048_managed_service_workflow.sql",
      import.meta.url,
    ),
    "utf8",
  );
  assert.match(
    migration48,
    /managed_content_concepts_strategy_tenant_company_fk/,
  );
  assert.match(
    migration48,
    /managed_planned_slots_adaptation_tenant_company_fk/,
  );
  assert.match(migration48, /managed_approval_requests_staff_write/);
  assert.match(migration48, /client_respond_managed_approval/);
  assert.match(migration48, /respond_managed_approval_with_token/);
  assert.match(migration48, /security definer/);
  assert.match(migration48, /target\.due_at <= stamp/);
  assert.match(migration48, /target\.superseded_by_id is not null/);
  assert.doesNotMatch(
    migration48,
    /managed_approval_requests_access[\s\S]*for all to authenticated/,
  );
  assert.match(
    migration48,
    /revoke select on managed_approval_requests from authenticated/,
  );
  const migration49 = readFileSync(
    new URL(
      "../supabase/legacy-migrations/0049_managed_content_jobs.sql",
      import.meta.url,
    ),
    "utf8",
  );
  assert.ok(
    migration49.indexOf("create table managed_content_job_exceptions") <
      migration49.indexOf("alter table managed_content_job_exceptions"),
  );

  const db = await import("../src/lib/db/index");
  const tenant = await db.createTenant({
    name: "Reminder claim test",
    kind: "agency",
    plan: "starter",
    status: "active",
  });
  const company = await db.createCompany({
    tenantId: tenant.id,
    name: "Reminder company",
    createdBy: "selftest",
  });
  const approval = await db.createManagedApprovalRequest({
    tenantId: tenant.id,
    companyId: company.id,
    contentId: null,
    conceptId: null,
    plannedSlotId: null,
    adCampaignId: null,
    scope: "standard_content",
    recipientEmail: "client@example.test",
    tokenHash: "hash",
    status: "pending",
    dueAt: "2026-07-20T00:00:00.000Z",
    revisionRound: 0,
    supersededById: null,
    reminder7dAt: null,
    reminder3dAt: null,
    staffEscalationAt: null,
    reminder7dKey: null,
    reminder3dKey: null,
    staffEscalationKey: null,
    respondedAt: null,
    directChargeDisclosureAcceptedAt: null,
  });
  const concurrentClaims = await Promise.all([
    db.claimManagedApprovalReminder(approval.id, "client_7d", "tick-a", stamp),
    db.claimManagedApprovalReminder(approval.id, "client_7d", "tick-b", stamp),
  ]);
  assert.equal(concurrentClaims.filter(Boolean).length, 1);
  const owner = concurrentClaims[0] ? "tick-a" : "tick-b";
  await db.completeManagedApprovalReminderClaim(
    approval.id,
    "client_7d",
    owner,
    "approval:test:client_7d",
  );
  assert.equal(
    await db.claimManagedApprovalReminder(
      approval.id,
      "client_7d",
      "retry",
      "2026-07-19T00:00:01.000Z",
    ),
    true,
  );
  const tokenApproval = await db.createManagedApprovalRequest({
    ...approval,
    tokenHash: "token-hash-two-revisions",
    status: "pending",
    revisionRound: 1,
    dueAt: "2099-07-20T00:00:00.000Z",
  });
  assert.equal(
    await db.respondManagedApprovalWithToken(
      tokenApproval.tokenHash,
      company.id,
      "changes_requested",
      { note: "second and final revision" },
    ),
    true,
  );
  assert.equal(
    await db.respondManagedApprovalWithToken(
      tokenApproval.tokenHash,
      company.id,
      "changes_requested",
      { note: "replay" },
    ),
    true,
  );
  const exhausted = await db.createManagedApprovalRequest({
    ...approval,
    tokenHash: "token-hash-exhausted",
    status: "pending",
    revisionRound: 2,
    dueAt: "2099-07-20T00:00:00.000Z",
  });
  assert.equal(
    await db.respondManagedApprovalWithToken(
      exhausted.tokenHash,
      company.id,
      "changes_requested",
    ),
    false,
  );
  await db.purgeTenant(tenant.id);
}

void reviewFindingChecks()
  .then(() => console.log("managed-service UX self-test passed"))
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
